(defun color-theme-vibrant-ink-win ()
  "Modified from Vivid Chalk, a vim port of Vibrant Ink."
  (interactive)
  (color-theme-install
   '(color-theme-vibrant-ink-win
     ((background-color . "#030303")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color .  "MediumOrchid1")
      (foreground-color . "#DDDDDB")
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight))
     (default ((t (nil))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (fringe ((t (:background "#090909"))))
     ;;(cursor ((t (:foreground "#404040") (:background "#404040")))) 
     (font-lock-builtin-face ((t (:foreground "#CCCC33"))))
     (font-lock-comment-face ((t (:italic t :foreground "#9933cc"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#9933cc"))))
     (font-lock-constant-face ((t (:foreground "#339999"))))
     (font-lock-function-name-face ((t (:foreground "#ffcc00"))))
     (font-lock-keyword-face ((t (:foreground "#ff6600"))))
     (font-lock-preprocessor-face ((t (:foreground "#aaffff"))))
     (font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-string-face ((t (:foreground "#59c82b"))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:italic t :foreground "#aaaaaa"))))
     (font-lock-variable-name-face ((t (:foreground "#aaccff"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (paren-face-match-light ((t (:background "#222222"))))
     (show-paren-match ((t (:background "MediumPurple" :foreground "white"))))
     (show-paren-mismatch ((t (:background "firebrick1" :foreground "white"))))
     (highlight ((t (:background "darkolivegreen"))))
     (italic ((t (:italic t))))
     (vertical-border ((t (:foreground "#404040"))))
     (mode-line ((t (:background "black" :foreground "MediumPurple"))))
     (mode-line-inactive ((t (:background "black" :foreground "#404040"))))
     (mode-line-buffer-id ((t (:bold t))))
     (mode-line-mousable ((t (:background "#a5baf1" :foreground
					 "black")))) 
     (mode-line-mousable-minor-mode ((t (:background
					"#a5baf1" :foreground "black"))))
     (region ((t (:background "#222244"))))
     (primary-selection ((t (:background "#555577"))))
     (isearch ((t (:foreground "#000000" :background "HotPink1"))))
     (lazy-highlight ((t (:foreground "#000000" :background "MediumPurple1"))))
     (zmacs-region ((t (:background "#555577"))))
     (secondary-selection ((t (:background "darkslateblue"))))
     (flymake-errline ((t (:background "LightSalmon" :foreground
				       "black"))))
     (flymake-warnline ((t (:background "LightSteelBlue" :foreground
					"black"))))
     (underline ((t (:underline t))))
     (minibuffer-prompt ((t (:bold t :foreground "#ff6600"))))
     (eshell-prompt ((t (:bold t :foreground "#9933cc"))))
     (twit-message-face ((default (:family "sans"  :height 1.0))))
     (twit-info-face ((t (:foreground "CornflowerBlue"))))
     (twit-title-face ((t  (:background "Cyan4"))))
     (twit-zebra-1-face ((t (:background "MidnightBlue"))))
     (twit-zebra-2-face ((t (:background "DarkSlateBlue"))))
     (ido-only-match ((((class color))
		       (:foreground "#ffcc00"))
		      (t (:italic t))))
     (ido-subdir ((((min-colors 88) (class color))
		   (:foreground "#339999"))
		  (((class color))
		   (:foreground "#339999"))
		  (t (:underline t))))
     (ido-first-match ((((class-color))
			(:foreground "IndianRed3"))
		       (t (:bold t))))
     (hi-blue ((t (:background "SkyBlue4" :foreground "White"))))
     (completions-first-difference ((t (:foreground "IndianRed3"))))
     ))) 